10.0 mig l10n it vat registries giuliano
eLBati/l10n-italy pull request #86
Opened 2017-02-04 12:27 UTC by Giuliano69

Ciao Lorenzo,
prima esperienza di PR su PR... non vorrei aver fatto errori ... ;-)) 
grazie ancora  di tutto l'aiuto....

Proposta :
- modificato il metodo on_change, del wizard di stamp, in modo tale che al cambiare di registro iva scelto, venga aggiornato il corrispondente layout di stampa registro in automatico
- rinominato la variabile del registro fattura "type", in quanto anche se non una keyword riservata, è  ufficialmente una built-in function:  https://docs.python.org/2.7/library/functions.html#type . (allibito che anche Odoo in invoice usi la variabile type...)

2017-02-07 10:17 UTC, eLBati requested changes
Ciao @Giuliano69 grazie mille della PR.
Vedi solamente la richiesta sul file org.eclipse.core.resources.prefs

2017-02-07 10:17 UTC, eLBati commented on .settings/org.eclipse.core.resources.prefs
> +encoding//l10n_it_vat_registries/wizard/print_registro_iva.py=utf-8
Dovresti rimuovere questo file

2017-02-09 07:58 UTC, eLBati commented
@Giuliano69 guarda il diff
https://github.com/eLBati/l10n-italy/pull/86/files

Le modifiche devono riguardare solo ```l10n_it_vat_registries```

2017-02-09 08:07 UTC, Giuliano69 commented
Ciao Lorenzo.
rimosso il config di eclipse e di pydev.

Nel .gitignore ho trovato le direttive per pycharm, ed ho aggiunto eclipse.... ma non eri un "eroico" del Geany ? :-)
Ti ha "contaminato" Davide ? :-)))))))

2017-02-09 08:18 UTC, Giuliano69 commented
Scusa, ho visto  adesso che avevi già notato la modifica.... mi sembra il problema derivi dai file .mo che vengono ignorati da git (SE ho capito il prolema)

Come dicevo ho toccato solamente il file .gitignore, aggiungendo le direttive per eclispe&pydev. 
Ho dato il comando "git rm --cached -r ." e poi "git add . " , perchè i files già presenti in cache, anche se escusi dal .gitignore, vengono altrimenti mantenuti.
git ha riapplicato anche _tutte_  le _vecchie_ direttive ed ha escluso i file .mo perchè erano stati precedentemente dichiarati da escludere (vecchio refuso ?) ......  forse la cache non era stata pulita fino ad oggi... 

Ma allora il problema è 
o nel .gitignore (che non deve escludere i .mo ), 
oppure i file erano rimasti li "dormienti" anche se da eliminare.....

il file .settings  è un file di servizio eclispe .... cancellato quello e cancelli ii progetto eclipse....; normalmente lo si tiene e lo si inserisce nel .gitignore (come per la direttiva .idea) 

Come devo procedere ?

2017-02-15 08:33 UTC, eLBati commented
Ciao @Giuliano69 
Per sintetizzare: questa PR deve contenere solo le modifiche riassunte nella descrizione.
Eventualmente, per altre modifiche tipo al .gitignore o altro, bisognerebbe fare delle PR dedicate, direttamente su OCA/l10n-italy
Grazie

2017-03-01 09:11 UTC, Giuliano69 commented
Ciao Lorenzo,
avendo modificato la cache di github e fatto il reindex, non riesco più a "rimettere  dentro" i file .mo, dato che nel file di configurazione git sono espressamente esclusi (deve trattarsi di un refuso per account_central_journal/i18n/it.mo  e per l10n_it_withholding_tax/i18n/it.mo )

Ho fatto un branch ex novo. con dentro i due refusi, e ho riapplicato le modifiche, escludendo il file .settings di Eclipse.

2017-03-01 09:11 UTC, closed without merging