[IMP] improved dictionary keys used for testing
eLBati/l10n-italy pull request #94
Opened 2017-05-11 14:37 UTC by gabriele-baldessari

Fix for account_invoice_report_ddt_group tests

2017-05-12 06:29 UTC, eLBati requested changes

2017-05-12 06:29 UTC, eLBati commented on account_invoice_report_ddt_group/tests/test_invoice_ddt_group.py
>          # }
Grazie @gabriele-baldessari , puoi modificare anche il commento qua sopra, per essere coerente con la nuova struttura del dizionario ? (ricorda poi di fare commit con --amend)

2017-05-23 08:32 UTC, alessandrocamilli approved these changes

2017-05-23 09:30 UTC, eLBati commented
Merged with
https://github.com/eLBati/l10n-italy/commit/4baa7ac28bfa1ec642ff236c1398623519368e18

2017-05-23 09:30 UTC, closed without merging